shell.run("rom/programs/http/pastebin get NSrf5fWY craplib.lua")
shell.run("rom/programs/http/pastebin get W8b3qbYf forest.lua")
shell.run("rom/programs/http/pastebin get QGBxP7SZ quarry.lua")
shell.run("rom/programs/http/pastebin get 0qCfYC9M stripMine.lua")
shell.run("rom/programs/http/pastebin get HKDGV344 tree.lua")
shell.run("rom/programs/http/pastebin get AiYbPpam update.lua")
